# Generated by Django 5.2.5 on 2025-09-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_news_shop_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='avtor',
            new_name='author',
        ),
    ]
